name: Tests (Unit)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.13]

    name: ${{ matrix.os }}, go ${{ matrix.go }}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - run: make test
